version: '3.6'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbroot
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  nginx:
    depends_on:
      - wordpress
    image: nginx:alpine
    ports:
      - "4443:443"
    restart: always
    volumes:
      - certificates:/etc/ssl/mount
      - ./nginx.conf:/etc/nginx/nginx.conf
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile-wordpress
      target: development
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    expose:
      - "80"
    restart: always
volumes:
  certificates:
    external: true
  db_data: {}
